// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xzCaSIi6Vr_-4RtcbiOsyFOVjGKpU6I',
    appId: '1:1048576351414:web:6abd3e98f60ad94716da17',
    messagingSenderId: '1048576351414',
    projectId: 'news-app-d7322',
    authDomain: 'news-app-d7322.firebaseapp.com',
    storageBucket: 'news-app-d7322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0mCX31nDCI-UhTQdD8XP9pVLIggbEMVQ',
    appId: '1:1048576351414:android:e2ec7b7764667f9916da17',
    messagingSenderId: '1048576351414',
    projectId: 'news-app-d7322',
    storageBucket: 'news-app-d7322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD61JSwD03pYdgazEIeVYezh7qAviwZ6bo',
    appId: '1:1048576351414:ios:f596d6913878964216da17',
    messagingSenderId: '1048576351414',
    projectId: 'news-app-d7322',
    storageBucket: 'news-app-d7322.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
